SO: main.c GerenciadorMemoria.cpp GerenciadorProcessos.cpp GerenciadorRecursos.cpp Processo.cpp Escalonador.cpp
	g++ -ansi -Wall -pedantic main.c GerenciadorMemoria.cpp GerenciadorProcessos.cpp GerenciadorRecursos.cpp -o SO.out Processo.cpp -std=c++11 Escalonador.cpp -fmax-errors=5
