SO: main.c GerenciadorMemoria.cpp GerenciadorProcessos.cpp GerenciadorRecursos.cpp Processo.cpp
	g++ -ansi -Wall -pedantic main.c GerenciadorMemoria.cpp GerenciadorProcessos.cpp GerenciadorRecursos.cpp -o SO Processo.cpp
